name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  

      - name: Setup Node.js
        uses: actions/setup-node@v2 
        with:
          node-version: '18'  

      - name: Install Dependencies
        run: npm install  

      - name: Build Project
        run: npm run build  

      # Etapa para construir a imagem Docker
      - name: Build Docker Image
        run: docker build -t mariagabrielly/backmobile:latest .

      # Etapa para fazer o login no Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Etapa para fazer o push da imagem para o Docker Hub
      - name: Push Docker Image
        run: docker push mariagabrielly/backmobile:latest
