name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Configure Docker
      uses: actions/setup-node@v3
      with:
        node-version: 14
    - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/your-docker-image-name .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/your-docker-image-name

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy your-service-name \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/your-docker-image-name \
          --platform managed \
          --allow-unauthenticated
